#!/bin/sh

# script/bootstrap: installs any dependencies
set -e

cd "$(dirname "$0")/.."

bundler_version="$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)"
echo "==> Installing bundler..."
gem install bundler -v $bundler_version
echo $(bundle --version)

if [ -f "Gemfile" ]; then
  echo "==> Installing gem dependencies…"
  bundle config set --local path 'vendor/gems'
  bundle config set --local without 'production'

  not_configured=$(bundle config GITHUB__COM | grep -q "not configured")
  if [ -z $not_configured ]; then
    echo "==> configuring access to ftf gems"
    bundle config --local GITHUB__COM $GITHUB_TOKEN:x-oauth-basic
  fi

  bundle lock --add-platform x86_64-linux
  bundle install
fi

echo "==> ready"
