#!/bin/sh

# script/console: Launch the console

# ensure everything in the app is up to date.
script/update

test -z "$RAILS_ENV" && RAILS_ENV='development'

# boot the app and any other necessary processes.
bundle exec rails c
